# Day 09. Exercise 02
# Metrics

## 0. Imports

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
  accuracy_score, 
  precision_score, 
  recall_score, 
  roc_auc_score
)

## 1. Preprocessing

1. Create the same dataframe as in the previous exercise.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test`. Use the additional parameter `stratify`.

In [1391]:
RANDOM_STATE = 21
TEST_SIZE = 0.2
PROBABILIY = True

In [1392]:
df = pd.read_csv("../data/day-of-week-not-scaled.csv")
prev_df = pd.read_csv("../data/dayofweek.csv")
df

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,9,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1682,6,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1683,7,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1684,8,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1685,9,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [1393]:
df.insert(0, 'dayofweek', prev_df['dayofweek'])
df

,dayofweek,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,4,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,4,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,4,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,3,9,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1682,3,6,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1683,3,7,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1684,3,8,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1685,3,9,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [1394]:
X = df.drop('dayofweek', axis=1)
y = df['dayofweek']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y)

## 2. SVM

1. Use the best parameters from the previous exercise and train the model of SVM.
2. You need to calculate `accuracy`, `precision`, `recall`, `ROC AUC`.

 - `precision` and `recall` should be calculated for each class (use `average='weighted'`)
 - `ROC AUC` should be calculated for each class against any other class (all possible pairwise combinations) and then weighted average should be applied for the final metric
 - the code in the cell should display the result as below:

```
accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878
```

In [1395]:
svc = SVC(C=10,
          kernel='rbf',
          gamma='auto',
          probability=True,
          class_weight=None,
          random_state=RANDOM_STATE)

svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)

In [1396]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average="weighted")
recall = recall_score(y_test, y_pred, average="weighted")
y_prob = svc.predict_proba(X_test)
roc_auc = roc_auc_score(y_test, y_prob, average="weighted", multi_class="ovo")

In [1397]:
print(f"accuracy is {accuracy:.5f}",
      f"precision is {precision:.5f}",
      f"recall is {recall:.5f}",
      f"roc_auc is {roc_auc:.5f}",
      sep="\n")

accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878

## 3. Decision tree

1. The same task for decision tree

In [1398]:
dtc = DecisionTreeClassifier(
  criterion='gini',
  max_depth=22,
  class_weight='balanced',
  random_state=RANDOM_STATE
)
dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)

In [1399]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average="weighted")
recall = recall_score(y_test, y_pred, average="weighted")
y_prob = dtc.predict_proba(X_test)
roc_auc = roc_auc_score(y_test, y_prob, average="weighted", multi_class="ovo")

In [1400]:
print(f"accuracy is {accuracy:.5f}",
      f"precision is {precision:.5f}",
      f"recall is {recall:.5f}",
      f"roc_auc is {roc_auc:.5f}",
      sep="\n")

accuracy is 0.89053
precision is 0.89262
recall is 0.89053
roc_auc is 0.93664

## 4. Random forest

1. The same task for random forest.

In [1401]:
rfc = RandomForestClassifier(
  n_estimators=50,
  criterion='gini',
  max_depth=28,
  class_weight=None,
  random_state=RANDOM_STATE
)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)

In [1402]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average="weighted")
recall = recall_score(y_test, y_pred, average="weighted")
y_prob = rfc.predict_proba(X_test)
roc_auc = roc_auc_score(y_test, y_prob, average="weighted", multi_class="ovo")

In [1403]:
print(f"accuracy is {accuracy:.5f}",
      f"precision is {precision:.5f}",
      f"recall is {recall:.5f}",
      f"roc_auc is {roc_auc:.5f}",
      sep="\n")

accuracy is 0.92899
precision is 0.93009
recall is 0.92899
roc_auc is 0.99033

## 5. Predictions

1. Choose the best model.
2. Analyze: for which `weekday` your model makes the most errors (in % of the total number of samples of that class in your full dataset), for which `labname` and for which `users`.
3. Save the model.

In [1404]:
final_df = pd.concat([
  pd.DataFrame({
    'weekday': y_test,
    'predicted_weekday': y_pred
  }),
  X_test.drop(['numTrials', 'hour'], axis=1)
], axis=1)
final_df['is_error'] = final_df['weekday'] != final_df['predicted_weekday']
final_df

,weekday,predicted_weekday,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,is_error
1087,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,False
16,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,False
563,6,6,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,False
1381,3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,False
1199,2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1411,3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,False
1079,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,False
1222,2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,False
1064,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,False
1243,2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,False

In [1405]:
weekday_errors = (
  final_df.groupby('weekday')['is_error']
  .mean() * 100
)

for weekday, error in weekday_errors.items():
  print(f"Weekday {weekday}: {error:.2f}% error")

Weekday 0: 25.93% error
Weekday 1: 10.91% error
Weekday 2: 6.67% error
Weekday 3: 2.50% error
Weekday 4: 14.29% error
Weekday 5: 5.56% error
Weekday 6: 1.41% error

In [1406]:
lab_cols = [col for col in final_df.columns if col.startswith("labname_")]

labs_long = final_df.melt(
  id_vars=["weekday", "predicted_weekday", "is_error"],
  value_vars=lab_cols,
  var_name="labname",
  value_name="active"
)

labs_active = labs_long[labs_long["active"] == 1]

labs_error = (
  labs_active.groupby("labname")["is_error"]
  .mean() * 100
)

for labname, error in labs_error.items():
  print(f"{labname}: {error:.2f}% error")

labname_code_rvw: 7.69% error
labname_lab03: 100.00% error
labname_lab03s: 100.00% error
labname_lab05s: 16.67% error
labname_laba04: 17.14% error
labname_laba04s: 0.00% error
labname_laba05: 2.13% error
labname_laba06: 22.22% error
labname_laba06s: 13.33% error
labname_project1: 4.84% error

In [1407]:
user_cols = [col for col in final_df.columns if col.startswith("uid_user_")]

users_long = final_df.melt(
    id_vars=["weekday", "predicted_weekday", "is_error"],
    value_vars=user_cols,
    var_name="user",
    value_name="active"
)

users_active = users_long[users_long["active"] == 1]

user_errors = (
    users_active.groupby("user")["is_error"]
    .mean() * 100
)

for user, error in user_errors.items():
  print(f"{user}: {error:.2f}% error")

uid_user_1: 0.00% error
uid_user_10: 8.33% error
uid_user_12: 0.00% error
uid_user_13: 0.00% error
uid_user_14: 3.23% error
uid_user_15: 0.00% error
uid_user_16: 40.00% error
uid_user_17: 0.00% error
uid_user_18: 16.67% error
uid_user_19: 21.05% error
uid_user_2: 3.57% error
uid_user_20: 0.00% error
uid_user_21: 0.00% error
uid_user_22: 100.00% error
uid_user_23: 0.00% error
uid_user_24: 9.09% error
uid_user_25: 9.09% error
uid_user_26: 0.00% error
uid_user_27: 16.67% error
uid_user_28: 0.00% error
uid_user_29: 9.09% error
uid_user_3: 14.29% error
uid_user_30: 12.50% error
uid_user_31: 11.11% error
uid_user_4: 7.41% error
uid_user_6: 25.00% error
uid_user_8: 0.00% error

## 6. Function

1. Write a function that takes a list of different models and a corresponding list of parameters (dicts) and returns a dict that contains all the 4 metrics for each model.

In [1408]:
def calculate_metrics(
    models: list,
    params: list[dict],
) -> dict:
  models_metrics = {}

  for model, parameters in zip(models, params):
    metrics = {}
    estimator = model(**parameters)
    estimator.fit(X_train, y_train)
    y_pred = estimator.predict(X_test)
    y_prob = estimator.predict_proba(X_test)


    metrics["accuracy"] = accuracy_score(y_test, y_pred)
    metrics["precision"] = precision_score(y_test, y_pred, average="weighted")
    metrics["recall"] = recall_score(y_test, y_pred, average="weighted")
    metrics["roc_auc"] = roc_auc_score(y_test, y_prob, average="weighted", multi_class="ovo")

    models_metrics[model.__name__] = metrics

  return models_metrics

In [1409]:
models = [SVC, DecisionTreeClassifier, RandomForestClassifier]
models_params = [
  { 'C':10,
    'kernel':'rbf',
    'gamma':'auto',
    'probability':True,
    'class_weight':None,
    'random_state':RANDOM_STATE
  },
  {
    'criterion':'gini',
    'max_depth':22,
    'class_weight':'balanced',
    'random_state':RANDOM_STATE
  },
  {
    'n_estimators':50,
    'criterion':'gini',
    'max_depth':28,
    'class_weight':None,
    'random_state':RANDOM_STATE
  }
]

In [1410]:
metrics = calculate_metrics(models, models_params)

for model_name, model_metrics in metrics.items():
  print(model_name)
  for key, value in model_metrics.items():
    print(f"{key} is {value:.5f}")
  print('\n')

SVC
accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878


DecisionTreeClassifier
accuracy is 0.89053
precision is 0.89262
recall is 0.89053
roc_auc is 0.93664


RandomForestClassifier
accuracy is 0.92899
precision is 0.93009
recall is 0.92899
roc_auc is 0.99033